reactjs/uk.react.dev

src/components/CodeEditor/CodeEditor.js, src/components/CodeExample/CodeExample.js, src/components/ErrorDecoder/ErrorDecoder.js, src/components/LayoutFooter/Footer.js, src/components/LayoutHeader/DocSearch.js, src/components/LayoutHeader/Header.js, src/components/MarkdownPage/MarkdownPage.js
This PR contains Ukrainian translation for components.
=> Translate components into Ukrainian

content/docs/reference-javascript-environment-requirements.md
**Reference JavaScript Environment translated** 👍
=> Reference JavaScript Environment translated

TRANSLATION.md
This PR will add a translation for the term "node" in the dictionary.
=> Термінологія: node

content/community/nav.yml, content/community/tools-data-fetching.md
=> Data Fetching to Отримання даних

content/community/nav.yml, content/community/tools-debugging.md
=> translated debugging-tools into Ukraine language

src/components/LayoutHeader/Header.js
=> Decrease the width of logo link

content/docs/hello-world.md
Just noticed that title wasn't translated.
=> Translate title in Hello World section

content/docs/cdn-links.md
Re-created #34 with adding requested changes.
Co-authored-by: ptaberg <34740585+ptaberg@users.noreply.github.com>
=> Translate into CDN Links document into Ukrainian

gatsby-config.js, src/pages/index.js
Co-authored-by: Kurzdor <pavloeksmidt@gmail.com>
Didn't get any response from @Kurzdor, so re-created #73 with adding requested changes.
=> Finished #73: Added translations for splash/title/website metadata in Gatsby config 

content/docs/getting-started.md
We haven't heard from @Kurzdor and @PetRichOst in a while, so I'm recreating a PRs #60 & #58 for "Getting Started" translationg with adding all requested changes.
Co-authored-by: Kurzdor pavloeksmidt@gmail.com
Co-authored-by: PetRichOst petroostapuk@gmail.com
=> Re-creating $58 & #60 (Getting Started)

content/docs/faq-build.md
=> Translate FAQ: Babel, JSX, and Build Steps into Ukrainian

content/docs/web-components.md
This PR contains a Ukrainian translation of Web components part of the advanced guides.
=> Translate "Web components" document into Ukrainian

content/docs/web-components.md
Reverts reactjs/uk.reactjs.org#107
=> Revert "Translate "Web components" document into Ukrainian"

content/docs/state-and-lifecycle.md
=> Updated sentence in do-not-modify-state-directly

content/docs/forms.md
=> Escape quote in code snippet

content/docs/hooks-reference.md
=> correct mistake in useContext description

content/docs/conditional-rendering.md
=> Correct the declension of the word

content/docs/context.md, examples/context/motivation-problem.js, examples/context/motivation-solution.js
This PR contains a part translation of Context document.
=> context page

src/content/learn/add-react-to-an-existing-project.md
`add-react-to-an-existing-project.md` translation
=> Finished translation of add-react-to-existing-project page

src/content/reference/react/hooks.md
This PR adds the Ukrainian translation for the "Hooks" page (`hooks.md`) in the React documentation.
Feedback is welcome! Happy to improve the PR if needed ✨
=> docs(uk): translate hooks.md to Ukrainian
